create extension if not exists pgcrypto;
create table if not exists public.notes (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,category text not null default '临时备忘',content text not null,pinned boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.todos (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,text text not null,done boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.notes enable row level security; alter table public.todos enable row level security;
drop policy if exists "notes_select_own" on public.notes; create policy "notes_select_own" on public.notes for select to authenticated using (auth.uid()=user_id);
drop policy if exists "notes_insert_own" on public.notes; create policy "notes_insert_own" on public.notes for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "notes_update_own" on public.notes; create policy "notes_update_own" on public.notes for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "notes_delete_own" on public.notes; create policy "notes_delete_own" on public.notes for delete to authenticated using (auth.uid()=user_id);
drop policy if exists "todos_select_own" on public.todos; create policy "todos_select_own" on public.todos for select to authenticated using (auth.uid()=user_id);
drop policy if exists "todos_insert_own" on public.todos; create policy "todos_insert_own" on public.todos for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "todos_update_own" on public.todos; create policy "todos_update_own" on public.todos for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "todos_delete_own" on public.todos; create policy "todos_delete_own" on public.todos for delete to authenticated using (auth.uid()=user_id);